import sys; sys.path.insert(0,'.')
from lift import Elf, Lifter, render_private
oem=Elf('/mnt/NVMe/git/scratch-clones/expo/tmp/oem-t21.ko')
ours=Elf(sys.argv[1])
ournames={s['name'] for s in ours.syms if s['name'] and s['shndx'] not in (0,) and s['type'] in (1,)}
ext={
 'system_reg_write':'system_reg_write(r_a0, r_a1); r_v0 = 0;',
 'system_reg_read':'r_v0 = (uint32_t)system_reg_read(r_a0);',
 'memset':'r_v0 = (uint32_t)(uintptr_t)memset((void *)(uintptr_t)r_a0, (int)r_a1, r_a2);',
 'memcpy':'r_v0 = (uint32_t)(uintptr_t)memcpy((void *)(uintptr_t)r_a0, (const void *)(uintptr_t)r_a1, r_a2);',
 'tisp_event_push':'r_v0 = (uint32_t)tisp_event_push((void *)(uintptr_t)r_a0);',
 'dma_cache_sync':'dma_cache_sync(NULL, (void *)(uintptr_t)r_a1, r_a2, (enum dma_data_direction)r_a3); r_v0 = 0;',
 '__ashldi3':'{ uint64_t v_ = (((uint64_t)r_a1 << 32) | r_a0) << (r_a2 & 63); r_v0 = (uint32_t)v_; r_v1 = (uint32_t)(v_ >> 32); }',
 '__lshrdi3':'{ uint64_t v_ = (((uint64_t)r_a1 << 32) | r_a0) >> (r_a2 & 63); r_v0 = (uint32_t)v_; r_v1 = (uint32_t)(v_ >> 32); }',
}
L=Lifter(oem, ournames, ext)
L.alias={'ev_changed@143d8':'tisp_adr_ev_changed','ev_now@143dc':'tisp_adr_ev_now','ev_changed@133ac':'tisp_defog_ev_changed','ev_now@133b0':'tisp_defog_ev_now'}
ournames|={'defog_fpga_para'}
todo=sys.argv[2].split(',')
done=[]; bodies=[]
while todo:
    f=todo.pop(0)
    if f in done: continue
    bodies.append(L.lift(f)); done.append(f)
    for nfn in L.need:
        if nfn not in done and nfn not in todo: todo.append(nfn)
    L.need=[]
# dispatch: every referenced function id must be lifted or extern
for fn in list(L.fnids):
    if fn not in done and fn not in ext:
        todo.append(fn)
while todo:
    f=todo.pop(0)
    if f in done: continue
    bodies.append(L.lift(f)); done.append(f)
    for nfn in L.need:
        if nfn not in done and nfn not in todo: todo.append(nfn)
    L.need=[]
disp=['static uint32_t L_dispatch(uint32_t fn, uint32_t r_a0, uint32_t r_a1, uint32_t r_a2, uint32_t r_a3, uint32_t sp_base)','{','\tuint32_t r_v0 = 0, r_v1 = 0;','\t(void)r_v1;','\tswitch (fn) {']
for fn,fid in L.fnids.items():
    if fn in ext: disp.append('\tcase 0x%xu: %s break;' % (fid, ext[fn]))
    else: disp.append('\tcase 0x%xu: r_v0 = L_%s(r_a0, r_a1, r_a2, r_a3, sp_base); break;' % (fid, fn))
disp+=['\tdefault: WARN_ON_ONCE(1); break;','\t}','\treturn r_v0;','}']
bodies.append('\n'.join(disp))
protos='\n'.join('static uint32_t L_%s(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);'%f for f in done)
print('/* Generated by lift.py from oem-t21.ko: %s */' % ', '.join(done))
print(render_private(L.private)); print(protos); print('static uint32_t L_dispatch(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);'); print('\n\n'.join(bodies))
sys.stderr.write('lifted %s\nprivate %s\n' % (done, list(L.private)))
