#!/usr/bin/env python3
"""Lift the stock T23 AE0 chain (tx-isp-t23.ko, md5 8237acb1...) into C.

usage: dolift_ae.py <stock tx-isp-t23.ko> > ../tx_isp_t23_ae_oem.inc
Uses the T21 translator (../../t21/audit/lift.py).  Every stock object the
chain touches becomes a private copy except tparams (the IQ bank, same
layout in this driver); hardware, sensor and event access goes through the
t23_aelift_* glue in tx_isp_t23_ae_oem_glue.inc.
"""
import io, os, re, sys
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 't21', 'audit'))
_buf = io.StringIO(); _real = sys.stdout; sys.stdout = _buf
from lift import Elf, Lifter, render_private
oem = Elf(sys.argv[1])
ext = {
 'system_irq_func_set': 'r_v0 = 0;',
 'tisp_event_set_cb': 'r_v0 = 0;',
 'tisp_event_push': 'r_v0 = (uint32_t)t23_aelift_event_push(r_a0, r_a1);',
 'private_complete': 'r_v0 = 0;',
 'private_kmalloc': 'r_v0 = (uint32_t)(uintptr_t)t23_aelift_kmalloc(r_a0);',
 'private_dma_cache_sync': 'private_dma_cache_sync(NULL, (void *)(uintptr_t)r_a1, r_a2, (enum dma_data_direction)r_a3); r_v0 = 0;',
 '__private_spin_lock_irqsave': '{ unsigned long f_; spin_lock_irqsave(&lift_lock, f_); *(uint32_t *)(uintptr_t)r_a1 = (uint32_t)f_; } r_v0 = 0;',
 'private_spin_unlock_irqrestore': 'spin_unlock_irqrestore(&lift_lock, (unsigned long)r_a1); r_v0 = 0;',
 'isp_printf': 'r_v0 = 0;',
 'printk': 'r_v0 = 0;',
 'dump_stack': 'r_v0 = 0;',
 'system_reg_write': 't23_aelift_reg_write(r_a0, r_a1); r_v0 = 0;',
 'system_reg_read': 'r_v0 = t23_aelift_reg_read(r_a0);',
 'memset': 'r_v0 = (uint32_t)(uintptr_t)memset((void *)(uintptr_t)r_a0, (int)r_a1, r_a2);',
 'memcpy': 'r_v0 = (uint32_t)(uintptr_t)memcpy((void *)(uintptr_t)r_a0, (const void *)(uintptr_t)r_a1, r_a2);',
 'div64_u64': '{ uint64_t q_ = div64_u64(((uint64_t)r_a1 << 32) | r_a0, ((uint64_t)r_a3 << 32) | r_a2); r_v0 = (uint32_t)q_; r_v1 = (uint32_t)(q_ >> 32); }',
 '__ashldi3': '{ uint64_t v_ = (((uint64_t)r_a1 << 32) | r_a0) << (r_a2 & 63); r_v0 = (uint32_t)v_; r_v1 = (uint32_t)(v_ >> 32); }',
 '__lshrdi3': '{ uint64_t v_ = (((uint64_t)r_a1 << 32) | r_a0) >> (r_a2 & 63); r_v0 = (uint32_t)v_; r_v1 = (uint32_t)(v_ >> 32); }',
}
L = Lifter(oem, {'tparams'}, ext, prefix='LA_')
L.tail_csp = True
L.callbacks = set()
L.cfuncs = set()
todo = os.environ.get('AE_FUNCS', 'tiziano_ae_init,tiziano_ae_dn_params_refresh,tisp_ae0_process,ae0_interrupt_static,ae0_interrupt_hist').split(',')
done = []; bodies = []
def drain():
    while todo:
        f = todo.pop(0)
        if f in done: continue
        bodies.append(L.lift(f)); done.append(f)
        for nfn in L.need:
            if nfn not in done and nfn not in todo: todo.append(nfn)
        L.need = []
drain()
fnames = {x['name'] for x in oem.syms if x['type'] == 2}
for fn in list(L.fnids) + sorted(L.fnaddr):
    if fn not in done and fn not in ext and fn in fnames:
        todo.append(fn)
drain()
disp = ['static uint64_t LA_dispatch(uint32_t fn, uint32_t r_a0, uint32_t r_a1, uint32_t r_a2, uint32_t r_a3, uint32_t sp_base)', '{']
for fn_ in done:
    disp.append('\tif (fn == (uint32_t)(uintptr_t)&LA_%s) return LA_%s(r_a0, r_a1, r_a2, r_a3, sp_base);' % (fn_, fn_))
# stock calls through a register holding an external function (jalr s0
# reused across calls): route those to the same glue as the direct calls
mapped = {ex_ for sz_, ex_ in L.vamap.values()}
for nm_ in sorted(ext):
    if any(('&%s ' % nm_) in m_ or ('&%s)' % nm_) in m_ for m_ in mapped):
        disp.append('\tif (fn == (uint32_t)(uintptr_t)&%s) { uint32_t r_v0 = 0, r_v1 = 0; %s return ((uint64_t)r_v1 << 32) | r_v0; }' % (nm_, ext[nm_]))
disp += ['\treturn t23_aelift_call(fn, r_a0, r_a1, r_a2, r_a3);', '}']
bodies.append('\n'.join(disp))
xl = ['static const struct lift_va { uint32_t va, size; uintptr_t ours; } lift_vamap[] = {']
for va_ in sorted(L.vamap):
    sz_, ex_ = L.vamap[va_]
    xl.append('\t{ 0x%xu, %du, (uintptr_t)%s },' % (va_, sz_, ex_))
xl.append('};')
xl.append('''static uint32_t lift_xlate(uint32_t va)
{
	int lo = 0, hi = ARRAY_SIZE(lift_vamap) - 1, best = -1;

	while (lo <= hi) {
		int mid = (lo + hi) / 2;

		if (lift_vamap[mid].va <= va) {
			best = mid;
			lo = mid + 1;
		} else {
			hi = mid - 1;
		}
	}
	if (best >= 0 && va - lift_vamap[best].va <= lift_vamap[best].size)
		return (uint32_t)(lift_vamap[best].ours + (va - lift_vamap[best].va));
	if (best + 1 < (int)ARRAY_SIZE(lift_vamap) &&
	    lift_vamap[best + 1].va - va <= 64)
		return (uint32_t)(lift_vamap[best + 1].ours -
				  (lift_vamap[best + 1].va - va));
	WARN_ONCE(1, "aelift: unmapped stock address %#x\\n", va);
	return va;
}
#define LIFT_XLATE(va) lift_xlate((uint32_t)(va))''')
print('/* SPDX-License-Identifier: GPL-2.0 */')
print('/* Generated by audit/dolift_ae.py from stock tx-isp-t23.ko (md5 8237acb18a548d8ad8c2d3fcf1517724): do not edit. */')
print('/* Lifted: %s */' % ', '.join(done))
print('static DEFINE_SPINLOCK(lift_lock);')
print(render_private(L.private))
print('\n'.join('static uint64_t LA_%s(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);' % f for f in done))
print('static uint64_t LA_dispatch(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);')
print('\n'.join(xl)); print('\n\n'.join(bodies))
sys.stderr.write('UNDEF %s\nlifted %d %s\nprivate %d\n' % (sorted(L.undef), len(done), done, len(L.private)))
sys.stdout = _real
out_ = re.sub(r'([A-Za-z_][A-Za-z0-9_]*)\.(isra|constprop|part)\.(\d+)', r'\1_\2_\3', _buf.getvalue())
# keep one C frame per stock frame: inlining would stack every inlined
# callee's frame[] into one kernel stack frame (24 KiB seen with GCC 16)
out_ = re.sub(r'^static uint64_t LA_', 'static noinline uint64_t LA_', out_, flags=re.M)
print(out_, end='')
